"""
medjar.report — renders the unified diagnostic report.

The report deliberately leads with status, red flags and disagreement before
the ranked differential: the clinically valuable information is what the system
is uncertain about.
"""
from __future__ import annotations

from typing import List, Sequence

from .schemas import CCO, CaseOutcome, ConsensusItem

_BANNER = (
    "> **Decision-support output.** Generated by the MedJar prototype for research "
    "demonstration on synthetic data. Not a diagnosis, not clinical advice, and not "
    "validated for patient care. A licensed clinician remains the decision-maker."
)


def _band(p: float) -> str:
    if p >= 0.70:
        return "high"
    if p >= 0.45:
        return "moderate"
    if p >= 0.20:
        return "low-moderate"
    return "low"


def render(cco: CCO, out: CaseOutcome, top_n: int = 5) -> str:
    L: List[str] = []
    A = L.append

    A(f"# MedJar Diagnostic Report — {out.case_id}")
    A("")
    A(_BANNER)
    A("")
    status_icon = "ESCALATED" if out.status == "escalated" else "CONVERGED"
    A(f"**Status:** `{status_icon}` — {out.reason}  ")
    A(f"**Rounds of debate:** {len(out.rounds) - 1} (plus independent proposal)  ")
    A(f"**Final ensemble disagreement:** D̄ = {out.rounds[-1].D_bar:.5f}  ")
    A(f"**Evidence ledger entries:** {len(out.ledger)}")
    A("")

    # --- 1. synthesis ---
    lead = out.consensus[0] if out.consensus else None
    A("## 1. Synthesis")
    A("")
    if lead:
        A(f"Leading impression: **{lead.dx}** (ICD-10 {lead.icd10}), "
          f"S\\* = {lead.S_star:.2f} ({_band(lead.S_star)} confidence), "
          f"with ensemble disagreement {lead.disagreement:.4f}.")
    else:
        A("No hypothesis reached the reporting threshold.")
    A("")

    # --- 2. red flags ---
    A("## 2. Can't-miss (red-flag) panel")
    A("")
    if out.red_flags:
        A("| Diagnosis | S\\* | Status |")
        A("|---|---|---|")
        for dx, s in sorted(out.red_flags.items(), key=lambda kv: -kv[1]):
            A(f"| **{dx}** | {s:.2f} | **requires urgent work-up** |")
        A("")
        A("These diagnoses triggered the escalation gate and must be actively excluded.")
    else:
        A("No can't-miss diagnosis exceeded the escalation threshold "
          "(τ_flag). This is *not* the same as exclusion — see recommended tests.")
    A("")

    # --- 3. differential ---
    A("## 3. Ranked differential")
    A("")
    A("| # | Diagnosis | ICD-10 | S\\* | S | E | Disagree | Discriminating test |")
    A("|---|---|---|---|---|---|---|---|")
    for n, i in enumerate(out.consensus[:top_n], 1):
        flag = " ⚑" if i.is_red_flag else ""
        A(f"| {n} | {i.dx}{flag} | {i.icd10} | **{i.S_star:.2f}** | {i.S:.2f} | "
          f"{i.E:+.2f} | {i.disagreement:.4f} | {i.discriminating_test or '—'} |")
    A("")
    A("`S` = confidence-weighted ensemble score (Eq. 1) · `E` = net grounded evidence · "
      "`S*` = evidence-adjusted score (Eq. 2) · `Disagree` = weighted variance (Eq. 3) · "
      "⚑ = can't-miss diagnosis.")
    A("")

    # --- 4. per-hypothesis evidence ---
    A("## 4. Evidence by hypothesis")
    A("")
    for i in out.consensus[:top_n]:
        A(f"### {i.dx} — S\\* {i.S_star:.2f}")
        A("")
        pa = ", ".join(f"{k} {v:.2f}" for k, v in sorted(i.per_agent.items()))
        A(f"*Per-agent likelihoods:* {pa}")
        A("")
        if i.supporting:
            A("**Supporting**")
            A("")
            for c in i.supporting:
                A(f"- {c.text} `[{c.citation_id}]` *(entailment {c.entailment:.2f})*")
            A("")
        if i.refuting:
            A("**Refuting / caveats**")
            A("")
            for c in i.refuting:
                A(f"- {c.text} `[{c.citation_id}]` *(entailment {c.entailment:.2f})*")
            A("")
        if i.discriminating_test:
            A(f"**Discriminating test:** {i.discriminating_test}")
            A("")

    # --- 5. disagreement ---
    A("## 5. Points of disagreement")
    A("")
    if out.open_disagreements:
        A("| Hypothesis | Weighted variance | Interpretation |")
        A("|---|---|---|")
        for dx, d in out.open_disagreements:
            interp = "specialists materially disagree" if d > 0.03 else "residual spread"
            A(f"| {dx} | {d:.4f} | {interp} |")
        A("")
        A("Disagreement is reported, never suppressed: it identifies exactly where "
          "clinician judgement is most needed.")
    else:
        A("The ensemble converged on the top hypotheses without material disagreement.")
    A("")

    # --- 6. debate trajectory ---
    A("## 6. Debate trajectory")
    A("")
    A("| Round | Phase | D̄ | Leading hypothesis | S\\* | Cumulative retrievals |")
    A("|---|---|---|---|---|---|")
    for rec in out.rounds:
        phase = "propose" if rec.round == 0 else "rebut"
        lead_dx = rec.top[0].dx if rec.top else "—"
        lead_s = f"{rec.top[0].S_star:.2f}" if rec.top else "—"
        A(f"| {rec.round} | {phase} | {rec.D_bar:.5f} | {lead_dx} | {lead_s} | {rec.retrievals} |")
    A("")

    # --- 7. recommended next steps ---
    A("## 7. Recommended next steps")
    A("")
    seen = set()
    n = 0
    for i in out.consensus[:top_n]:
        t = i.discriminating_test
        if not t or t in seen:
            continue
        seen.add(t)
        n += 1
        urgency = "**urgent** — " if i.is_red_flag and i.S_star >= 0.30 else ""
        A(f"{n}. {urgency}{t} — to discriminate *{i.dx}* (currently S\\* {i.S_star:.2f}).")
    A("")

    # --- 8. audit ---
    A("## 8. Audit trail")
    A("")
    A(f"Evidence ledger contains {len(out.ledger)} provenance-linked citations. "
      "Each entry records the retrieved passage, its source, publication year, "
      "evidence grade, retrieval scores, the citing agent and the hypothesis it "
      "was used for. The full debate transcript is replayable from the logged inputs.")
    A("")
    A("| Citation | Source | Year | Grade | Cited by | Hypothesis | Polarity |")
    A("|---|---|---|---|---|---|---|")
    for e in out.ledger[:14]:
        A(f"| `{e.citation_id}` | {e.source} — {e.section} | {e.publish_year} | "
          f"{e.evidence_grade} | {e.used_by_agent} | {e.hypothesis} | {e.polarity} |")
    if len(out.ledger) > 14:
        A(f"| … | *({len(out.ledger) - 14} further entries)* | | | | | |")
    A("")
    return "\n".join(L)


def render_transcript(out: CaseOutcome) -> str:
    """Full debate transcript, for the audit appendix."""
    L: List[str] = [f"# Debate transcript — {out.case_id}", ""]
    for rec in out.rounds:
        L.append(f"## Round {rec.round} · D̄ = {rec.D_bar:.5f}")
        L.append("")
        for t in rec.turns:
            L.append(f"### {t.agent} ({t.specialty}) — phase `{t.phase}`, "
                     f"confidence {t.confidence:.2f} (raw {t.confidence_raw:.2f})")
            L.append("")
            for h in t.hypotheses[:4]:
                L.append(f"- **{h.dx}** p={h.likelihood:.3f} · "
                         f"{len(h.supporting)} supporting / {len(h.refuting)} refuting citations")
            if t.red_flags:
                L.append(f"- red flags raised: {', '.join(t.red_flags)}")
            if t.critiques:
                L.append("")
                L.append("  Critiques issued:")
                for c in t.critiques[:6]:
                    L.append(f"  - → *{c.target_agent}* on **{c.dx}** "
                             f"[{c.kind}, severity {c.severity:.2f}]: {c.argument}")
            L.append("")
    return "\n".join(L)
