"""
pptx_slides.py — slide content for the PowerPoint build.

Kept separate from the OOXML rendering machinery in build_pptx.py so the deck
text can be edited without touching the file-format code.

Each entry is (running_header, title, [bullet lines]); an empty string inserts
vertical space. Text is deliberately ASCII-leaning: the PPTX is the text-only
companion to the figure-driven HTML deck, and glyphs such as combining macrons
render inconsistently across PowerPoint font stacks. Figures live in figures/
and are embedded in presentation.html and PAPER.md.
"""
from __future__ import annotations

from typing import List, Tuple

SLIDES: List[Tuple[str, str, List[str]]] = [
    ("MULTI-AGENT CLINICAL REASONING  ·  RESEARCH SEMINAR",
     "MedJar: Consensus Diagnosis by Debating Specialist Agents",
     ["Persona-conditioned language-model specialists reason independently over a",
      "patient case, ground every claim in retrieved literature, and are driven",
      "toward a calibrated, auditable diagnosis through structured debate.",
      "",
      "Radiologist  ·  Cardiologist  ·  Oncologist  ·  Generalist",
      "Assistive  ·  human-in-the-loop  ·  not an autonomous diagnostic device"]),

    ("MOTIVATION",
     "Diagnostic error is a systems problem",
     ["~5% of adults experience a diagnostic error in outpatient care each year",
      "Anchoring - an initial impression suppresses competing hypotheses",
      "Premature closure - the search ends once a plausible answer appears",
      "Specialty siloing - the experts who would resolve the case never meet on it",
      "Knowledge drift - guidelines change faster than any individual tracks them",
      "",
      "Medicine's countermeasure is the tumour board. What makes it work is not",
      "consensus but STRUCTURED DISAGREEMENT. Can that be made computational?"]),

    ("MOTIVATION",
     "Why a single model is insufficient",
     ["Correlated failure - one prior yields one blind spot, with no internal adversary",
      "Miscalibrated confidence - self-consistent but wrong, asserted confidently",
      "Unverifiable grounding - claims not bound to a source cannot be audited",
      "",
      "Majority voting does not fix this: it discards WHY agents differ and",
      "systematically silences the minority can't-miss diagnosis - the most",
      "consequential error mode in acute care."]),

    ("CONTRIBUTIONS",
     "Contributions",
     ["1. Specialist multi-agent formulation with private, specialty-scoped retrieval",
      "2. A structured debate protocol operating on grounded reasons",
      "3. A consensus formalism: weighted aggregation, evidence adjustment, and a",
      "    disagreement metric driving an explicit stopping / escalation rule",
      "4. A competence-scoped critique rule shown to be NECESSARY for safety",
      "5. A complete deterministic prototype, with negative results reported"]),

    ("SYSTEM  ·  ARCHITECTURE",
     "Six layers, one control loop",
     ["0 - Intake: de-identification, normalisation, ontology coding",
      "1 - Representation: multimodal encoders -> Case Context Object (CCO)",
      "2 - Knowledge: hybrid retrieval over a versioned, evidence-graded corpus",
      "3 - Reasoning: specialist agents and the debate loop (only stochastic stage)",
      "4 - Consensus: Eqs. (1)-(3), stopping rule, escalation gate",
      "5 - Reporting: ranked differential, provenance, replayable audit trail",
      "",
      "See Figure 1 (figures/fig01_architecture.svg)"]),

    ("SYSTEM  ·  WORKFLOW",
     "The complete workflow, end to end (steps 1-16)",
     ["Sources -> 1 ingest & normalise -> 2 de-identify   [PHI TRUST BOUNDARY]",
      "3 encode modalities -> 4 Case Context Object",
      "5 corpus index -> 6 RRF fusion & re-rank -> 7 groundedness gate -> Ledger",
      "8 independent proposal: agents retrieve privately, do not see each other",
      "9 align hypothesis space -> 10 critique -> 11 rebut -> 12 assess   [LOOP]",
      "13 Eq.1 S(h) -> Eq.2 S*(h) -> Eq.3 D-bar -> 14 stopping rule",
      "15 diagnostic report -> 16 clinician review and mandatory sign-off",
      "",
      "See Figure 2 (figures/fig02_workflow.svg) - the full swimlane diagram"]),

    ("SYSTEM  ·  REPRESENTATION",
     "Everything normalises into the Case Context Object",
     ["Structured EHR (FHIR/HL7) -> labs, meds, problems, coded to LOINC/ICD/RxNorm",
      "Clinical notes -> de-identified, section-parsed, negation-extracted",
      "Imaging (DICOM) -> vision findings; raw pixels never leave the enclave",
      "Pathology, genomics (VCF), ECG and waveform features",
      "",
      "Explicit NEGATIONS are carried, so agents can distinguish 'absent' from",
      "'not assessed' - a distinction lost when notes are flattened into text."]),

    ("METHOD  ·  GROUNDING",
     "Hybrid retrieval, then a hard grounding gate",
     ["Dense vector search for semantic recall",
      "Okapi BM25 for exact clinical terms, drug names, gene symbols",
      "Reciprocal rank fusion:  RRF(d) = SUM 1 / (k + rank_s(d)),  k ~ 60",
      "Cross-encoder re-ranking for precision; specialty and recency boosting",
      "",
      "GROUNDEDNESS GATE: a claim not entailed by its cited passage is excluded",
      "from aggregation. Survivors are written to the append-only Evidence Ledger."]),

    ("METHOD  ·  AGENTS",
     "The specialist ensemble",
     ["Radiologist  - morphology -> localisation -> imaging differential",
      "Cardiologist - exclude life-threatening cardiac aetiology first",
      "Oncologist   - tissue of origin, staging, biomarkers, tempo",
      "Generalist   - whole-patient coherence; guards against over-specialisation",
      "",
      "Scoped retrieval keeps perspectives distinct. Global retrieval would return",
      "the same passages to everyone and homogenise the ensemble."]),

    ("METHOD  ·  CONTRACT",
     "Structured turns and a shared hypothesis space",
     ["Every turn returns structured output, never free prose: per-hypothesis",
      "likelihood, supporting and refuting claims bound to citation ids, the",
      "discriminating next test, red flags, and calibrated confidence.",
      "",
      "AGENTS NEVER ABSTAIN. An agent with no prior for a hypothesis registers a",
      "low cautionary floor, lifted slightly for can't-miss diagnoses. Floors count",
      "in S(h) with reduced weight but are EXCLUDED from the disagreement metric:",
      "absence of an opinion is not dissent."]),

    ("METHOD  ·  DEBATE",
     "Propose -> critique -> rebut -> assess",
     ["1 PROPOSE - isolated. No cross-talk, so early anchoring cannot spread.",
      "2 CRITIQUE - anonymised and grounded: missing confirmation, overcall,",
      "    or alternative (the last reserved to the generalist).",
      "3 REBUT - concede, defend, or revise. Defence scales with grounded citations.",
      "    Contested points seed TARGETED RE-RETRIEVAL: disagreement does work.",
      "4 ASSESS - recompute S*, D-bar, red flags; apply the stopping rule.",
      "",
      "At least one critique round always runs: coinciding impressions are still",
      "cross-examined. See Figure 5 (figures/fig04_debate_sequence.svg)"]),

    ("METHOD  ·  CRITIQUE ADMISSIBILITY",
     "The right to object is tied to competence",
     ["An 'overcall' critique is admissible ONLY if the critic holds a genuine",
      "prior for that diagnosis. Every critique's severity scales with w_i(h).",
      "",
      "This is not a detail. Without it, three agents with no cardiology competence",
      "drove a correct acute coronary syndrome diagnosis from S* 0.84 to 0.27 -",
      "below the escalation threshold - and the case converged instead of",
      "escalating. An agent's ignorance is not evidence.",
      "",
      "See slide 'Four failure modes', item (b)."]),

    ("METHOD  ·  CONSENSUS",
     "Consensus formalism",
     ["Eq. 1   S(h)  = SUM_i w_i(h) c_i p_i(h)  /  SUM_i w_i(h) c_i",
      "Eq. 2   S*(h) = sigma( alpha * logit S(h) + beta * E(h) )",
      "Eq. 3   Disagree(h) = SUM_i w c (p_i - S)^2 / SUM_i w c,  over substantive i",
      "",
      "w_i(h) - soft mixture-of-experts weight: 1.00 in-domain, 0.58-0.82 adjacent,",
      "    0.45 otherwise. Not a router - every agent votes on every hypothesis.",
      "c_i - calibrated confidence.   E(h) - grade-, recency- and entailment-weighted",
      "    net evidence.   D-bar - mean of Eq. 3 over the top-3 hypotheses."]),

    ("METHOD  ·  CONTROL",
     "Deterministic orchestration and the stopping rule",
     ["Control flow is a finite-state machine, NOT a model: predictable, testable,",
      "auditable. It anonymises critiques, enforces the contract, rejects ungrounded",
      "turns, owns the Evidence Ledger, and enforces compute budgets.",
      "",
      "CONVERGE    D-bar <= tau_agree        -> aggregate and report",
      "BUDGET      r = R_max                 -> escalate, stating the disagreement",
      "CAN'T-MISS  red-flag dx S* >= tau_flag -> escalate, overriding consensus",
      "",
      "The override is asymmetric: it can force escalation, never suppress it.",
      "tau_agree = 0.010   tau_flag = 0.30   R_max = 4   r_min = 1"]),

    ("METHOD  ·  OUTPUT",
     "The report leads with uncertainty",
     ["Status banner (converged / escalated, with the reason)",
      "1 synthesis  ·  2 can't-miss panel  ·  3 ranked differential with S*, S, E",
      "4 evidence per hypothesis  ·  5 points of disagreement",
      "6 debate trajectory  ·  7 next steps  ·  8 audit trail",
      "",
      "The ordering is a SAFETY decision, not a stylistic one: the clinically",
      "valuable content is what the system is uncertain about. Disagreement is",
      "surfaced, never suppressed - it marks where judgement is needed."]),

    ("SYSTEM  ·  DEPLOYMENT",
     "Trust boundaries",
     ["PHI ENCLAVE - source systems, de-identification, token map, raw pixels,",
      "    immutable access audit log",
      "REASONING ZONE - de-identified CCO only: agent runtime, orchestrator,",
      "    retrieval service, Evidence Ledger, consensus and calibration",
      "CLINICAL REVIEW - report re-identified on demand, then mandatory sign-off",
      "",
      "No patient identifier crosses into the reasoning zone; every access is",
      "audited. See Figure 9 (figures/fig09_deployment.svg)"]),

    ("PROTOTYPE",
     "A complete, dependency-free implementation",
     ["schemas.py    CCO, hypotheses, claims, ledger entries",
      "corpus.py     24-passage versioned, evidence-graded corpus",
      "retrieval.py  BM25 + dense index + RRF fusion + re-ranker",
      "verify.py     groundedness gate       agents.py   personas and critique",
      "consensus.py  Eqs. (1)-(3), ECE/Brier debate.py   Chief-of-Service FSM",
      "",
      "No third-party dependencies, fully deterministic - the debate and consensus",
      "mathematics can be verified without a model in the loop. Two interchangeable",
      "back-ends: RuleBasedEngine (offline) and LLMEngine (production path).",
      "",
      "  cd prototype && python3 run_demo.py     |     cd figures && python3 make_figures.py"]),

    ("RESULTS",
     "What the prototype does (3 synthetic cases)",
     ["CASE-001  primary lung malignancy   S* 0.79 (hit)  4 rounds  ESCALATED",
      "CASE-002  benign granuloma          S* 0.59 (hit)  2 rounds  CONVERGED",
      "CASE-003  acute coronary syndrome   S* 0.55 (hit)  1 round   ESCALATED",
      "",
      "Top-1 3/3   Top-3 3/3   claims passing grounding gate 130/130   ledger 91",
      "ECE 0.243   Brier 0.077",
      "",
      "The three cases exercise all three stopping paths. THREE SYNTHETIC CASES",
      "WITH A DETERMINISTIC REASONER: this validates mechanism, not diagnostic",
      "performance. The 3/3 hit rate carries no clinical weight."]),

    ("RESULTS",
     "Disagreement works as a control signal",
     ["CASE-002  D-bar 0.0112 -> 0.0104 -> 0.0093   falls below tau_agree: CONVERGES",
      "CASE-001  D-bar 0.0384 -> 0.0345 (plateau)   specialists narrow but cannot",
      "          reconcile, so the case ESCALATES with its open disagreement stated",
      "CASE-003  D-bar 0.0037 -> 0.0034   agrees early, yet still escalates because",
      "          a can't-miss diagnosis overrides consensus",
      "",
      "D-bar gives a principled, compute-bounded criterion for",
      "'we are not sure - ask a human'.  See Figure 10."]),

    ("RESULTS",
     "Evidence adjustment does real work",
     ["The gap between S and S* is the contribution of grounded evidence.",
      "",
      "Primary lung malignancy      GAINS:  E = +0.72,  S 0.72 -> S* 0.79",
      "Malignant pericardial eff.   LOSES:  E = -0.34,  S 0.37 -> S* 0.33",
      "",
      "The retrieved guidance states that cytological confirmation is required",
      "before that classification - the corpus actively argues against asserting it.",
      "Plausibility and support are thereby separated.  See Figure 12."]),

    ("RESULTS  ·  NEGATIVE RESULT",
     "Calibration is not yet met",
     ["ECE = 0.243 over 19 hypothesis-level predictions. This is POOR, and we",
      "report it plainly.",
      "",
      "The temperatures and the coefficients alpha, beta are hand-set, not fitted",
      "on held-out data, so S* carries no calibration guarantee.",
      "",
      "Because Eq. (1) weights agents BY their confidence, this requirement is",
      "currently unmet. S* should be read ordinally, not as a probability.",
      "Fitting the calibration layer is the first prerequisite for any",
      "performance claim.  See Figure 13."]),

    ("FINDINGS",
     "Four failure modes the implementation exposed",
     ["(a) HYPOTHESES FLOATING ON THEIR PRIOR - a diagnosis with no supporting",
      "    feature present still scored ~0.33 on its intercept alone.",
      "(b) INCOMPETENT CRITIQUE -> FALSE REASSURANCE - agents with no cardiology",
      "    competence drove a correct ACS diagnosis from 0.84 to 0.27, below",
      "    tau_flag; the case converged instead of escalating.",
      "(c) UNBOUNDED REINFORCEMENT -> ECHO CHAMBER - uncontested positions inflated",
      "    every round, so apparent disagreement drifted upward.",
      "(d) IGNORANCE FLOORS COUNTED AS DISSENT - floors never move, creating",
      "    irreducible disagreement; the benign case failed to converge.",
      "",
      "All four are fixed in the code and reflected in the reported results."]),

    ("FINDINGS",
     "Aggregation rules, not agent count, determine safety",
     ["Failure (b) is the transferable result.",
      "",
      "An unweighted debate among heterogeneous agents is not merely noisier than",
      "a single competent agent - it can be systematically MORE DANGEROUS, because",
      "it provides a mechanism for confident non-experts to overrule a correct",
      "specialist.",
      "",
      "Debate is only safe if the right to object is tied to competence."]),

    ("EVALUATION",
     "The study this is not (yet)",
     ["Data: knowledge probes (MedQA, MedMCQA, PubMedQA); clinicopathological-",
      "    conference cases with confirmed diagnoses; a prospective SILENT TRIAL,",
      "    read-only, never influencing care",
      "Primary endpoint is SAFETY, not accuracy: can't-miss recall and the",
      "    false-reassurance rate",
      "Also: ECE / Brier, groundedness, blinded specialist ratings,",
      "    rounds-to-converge, and accuracy / calibration parity across subgroups",
      "Ablations: single agent | majority vote | debate without RAG |",
      "    without calibration | full system"]),

    ("SAFETY  ·  ETHICS  ·  REGULATORY",
     "Assistive by design - the clinician decides",
     ["Mandatory clinician sign-off before any recommendation informs care",
      "Uncertainty and can't-miss findings escalate rather than closing a case",
      "De-identification at intake, PHI enclave, encryption, per-access audit;",
      "    no training on patient data absent explicit governance and consent",
      "Likely Software as a Medical Device: transparent evidence and a replayable",
      "    transcript support independent clinician review, but deployment needs",
      "    clinical validation, change control, and post-market surveillance",
      "Equity: stratified corpus and evaluation, per-subgroup calibration monitoring"]),

    ("LIMITATIONS",
     "Limitations and threats to validity",
     ["Three synthetic cases, rule-based reasoner - mechanism only. No LLM in the",
      "    loop, no real patient data, no clinician review.",
      "Calibration unmet (ECE 0.243) - weighted aggregation is sound only once",
      "    c_i is fitted.",
      "Surrogate components - hashed bag-of-words embeddings, lexical-coverage",
      "    entailment, term-overlap re-ranking. Each would change absolute numbers.",
      "Crude polarity classification - ACS received E = -0.41 because passages",
      "    DEFINING its criteria contain cautionary language.",
      "Correlated agent failure, corpus gaps, automation bias, and compute cost",
      "    all remain open."]),

    ("CONCLUSION",
     "Conclusion",
     ["MedJar recasts the multidisciplinary case conference as a computational",
      "protocol: specialists reason independently, ground every claim, debate under",
      "rules that tie the right to object to competence, and converge on a",
      "calibrated, auditable assessment - escalating to a human precisely when",
      "they should.",
      "",
      "Demonstrated: the full pipeline runs end to end, deterministically, and",
      "D-bar functions as a control signal across all three stopping paths.",
      "",
      "Next: fit the calibration layer, then a prospective silent trial - the only",
      "way to learn whether any of this helps a clinician."]),

    ("ARTEFACTS",
     "Where everything lives",
     ["PAPER.md              the full technical report, with all 14 figures",
      "presentation.html     figure-driven deck, self-contained (open in a browser)",
      "figures/*.svg         14 vector figures + make_figures.py that generates them",
      "prototype/            the runnable system; run_demo.py reproduces the results",
      "prototype/output/     generated reports, debate transcripts, trace.json",
      "",
      "This PPTX is the text-only companion. The figures - including the full",
      "end-to-end workflow diagram - are in figures/ and embedded in PAPER.md",
      "and presentation.html.",
      "",
      "Decision support only. Not a medical device."]),
]
